server:
  port: 9999
  servlet:
    context-path: /
spring:
  main:
    allow-bean-definition-overriding: true
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://bj-cdb-9amt73r4.sql.tencentcdb.com:59997/koala?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
  #    username: test
  #    password: test@5015021301
  jackson:
    serialization:
      write-dates-as-timestamps: true
      indent_output: true
      fail_on_empty_beans: false
    default-property-inclusion: non_empty
    deserialization:
      fail_on_unknown_properties: false
  data:
    web:
      pageable:
        page-parameter: pageNumber
        size-parameter: pageSize
        default-page-size: 50
        max-page-size: 2000
      sort:
        sort-parameter: sort

logging:
  level:
    cn.koala: debug
  file:
    name: koala-sample-eucalyptus.log