server:
  port: 9999
  servlet:
    context-path: /
spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      write-dates-as-timestamps: true #设置返回日期为时间戳，方便前台格式化
      indent_output: true   #格式化输出
      fail_on_empty_beans: false #忽略无法转换的对象
    default-property-inclusion: non_empty #设置空值不序列化
    deserialization:
      fail_on_unknown_properties: false  #反序列化未知属性不失败
  data:
    web:
      pageable:
        page-parameter: pageNumber #分页设置-页码参数名称
        size-parameter: pageSize   #分页设置-页大小参数名称
        default-page-size: 50      #分页设置-默认页大小
        max-page-size: 2000        #分页设置-最大页大小
      sort:
        sort-parameter: sort       #分页设置-排序参数名称

logging:
  level:
    cn.houtaroy.koala: debug
  file:
    name: koala-sample-system-management.log